# Generated by Django 6.0.4 on 2026-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
