# Generated by Django 6.0.4 on 2026-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_farmerprofile_is_completed_alter_farmerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farming',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='land_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
