# Generated by Django 6.0.5 on 2026-05-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
