# Generated by Django 6.0.5 on 2026-05-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
